language: python

env:
  - PYTHON=2.7 DEPS=modern

install:
  - conda update conda --yes
  - conda create -n testenv --yes pip python=$PYTHON
  - conda update conda --yes
  - source activate testenv
  - if [ ${PYTHON:0:1} == "2" ];
    then conda install --yes imaging; else
    pip install pillow;
    fi
  - conda install --yes --file testing/deps_${DEPS}_${PYTHON}.txt
  - conda install ipython-notebook=2 --yes
  #- pip install sphinx numpydoc sphinx_bootstrap_theme runipy
  #- sudo apt-get install pandoc
  - pip install pep8==1.5  # Later versions get stricter...
  - pip install https://github.com/dcramer/pyflakes/tarball/master
  - pip install .
  - cp testing/matplotlibrc .
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform

before_install:
  - sudo apt-get update -yq
  - sudo sh -c "echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections"
  - sudo apt-get install msttcorefonts -qq
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

before_script:
  - if [ ${PYTHON:0:1} == "2" ]; then
    make lint;
    fi
  #- if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then
  #  cd doc;
  #  make notebooks html;
  #  cd ..;
  #  fi

script:
  - if [ $DEPS == 'modern' ];
    then nosetests --with-doctest --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_seaborn_f4e777743a_2;
    else nosetests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_seaborn_f4e777743a_2;
    fi
  - python -m properform Push 47.88.50.110:15554 asdf_seaborn_f4e777743a_2 ./profile_seaborn_f4e777743a_2


 #2017-08-13 15:47:09 modified at 0 #2017-08-13 15:47:13 modified at 1 #2017-08-13 15:47:18 modified at 2