language: python

env:
  - PYTHON=2.7 DEPS=modern

install:
  - conda update conda --yes
  - conda create -n testenv --yes pip python=$TRAVIS_PYTHON_VERSION
  - conda update conda --yes
  - source activate testenv
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ];
    then conda install --yes imaging; else
    pip install pillow;
    fi
  - conda install --yes --file testing/deps_${DEPS}.txt
  - pip install sphinx numpydoc sphinx_bootstrap_theme runipy
  - sudo apt-get install pandoc
  - pip install pep8
  - pip install https://github.com/dcramer/pyflakes/tarball/master  
  - pip install .
  - cp testing/matplotlibrc .
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform


before_install:
  - sudo apt-get update -yq
  - sudo sh -c "echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections"
  - sudo apt-get install msttcorefonts -qq
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then
    wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh; else
    wget http://repo.continuum.io/miniconda/Miniconda3-2.2.2-Linux-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

before_script:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then
    make lint;
    fi
  #- if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then
  #  cd doc;
  #  make notebooks html;
  #  cd ..;
  #  fi

script:
  - nosetests --with-doctest --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_seaborn_5746223894_2
  # Notebook tests are failing on old matplotlib
  # because the figures have every so slightly a
  # different size. Skip until I understand why.
  - if [ ${DEPS} == modern ]; then
    python ipnbdoctest.py examples/*.ipynb;
    fi
  - python -m properform Push 47.88.50.110:15554 asdf_seaborn_5746223894_2 ./profile_seaborn_5746223894_2



 #2017-08-13 16:24:23 modified at 0 #2017-08-13 16:24:28 modified at 1 #2017-08-13 16:24:32 modified at 2